class Share {

    avgTotalVolume;
    calculationPrice;
    change;
    changePercent;
    close;
    closeSource;
    closeTime;
    companyName;
    currency;
    delayedPrice;
    delayedPriceTime;
    extendedChange;
    extendedChangePercent;
    extendedPrice;
    extendedPriceTime;
    high;
    highSource;
    highTime;
    iexAskPrice;
    iexAskSize;
    iexBidPrice;
    iexBidSize;
    iexClose;
    iexCloseTime;
    iexLastUpdated;
    iexMarketPercent;
    iexOpen;
    iexOpenTime;
    iexRealtimePrice;
    iexRealtimeSize;
    iexVolume;
    lastTradeTime;
    latestPrice;
    latestSource;
    latestTime;
    latestUpdate;
    latestVolume;
    low;
    lowSource;
    lowTime;
    marketCap;
    oddLotDelayedPrice;
    oddLotDelayedPriceTime;
    open;
    openTime;
    openSource;
    peRatio;
    previousClose;
    previousVolume;
    primaryExchange;
    symbol;
    volume;
    week52High;
    week52Low;
    ytdChange;
    isUSMarketOpen;

    constructor(avgTotalVolume, calculationPrice, change, changePercent, close, closeSource, closeTime, companyName, currency, delayedPrice, delayedPriceTime, extendedChange, extendedChangePercent, extendedPrice, extendedPriceTime, high, highSource, highTime, iexAskPrice, iexAskSize, iexBidPrice, iexBidSize, iexClose, iexCloseTime, iexLastUpdated, iexMarketPercent, iexOpen, iexOpenTime, iexRealtimePrice, iexRealtimeSize, iexVolume, lastTradeTime, latestPrice, latestSource, latestTime, latestUpdate, latestVolume, low, lowSource, lowTime, marketCap, oddLotDelayedPrice, oddLotDelayedPriceTime, open, openTime, openSource, peRatio, previousClose, previousVolume, primaryExchange, symbol, volume, week52High, week52Low, ytdChange, isUSMarketOpen,) {

        this.avgTotalVolume = avgTotalVolume;
        this.calculationPrice = calculationPrice;
        this.change = change;
        this.changePercent = changePercent;
        this.close = close;
        this.closeSource = closeSource;
        this.closeTime = closeTime;
        this.companyName = companyName;
        this.currency = currency;
        this.delayedPrice = delayedPrice;
        this.delayedPriceTime = delayedPriceTime;
        this.extendedChange = extendedChange;
        this.extendedChangePercent = extendedChangePercent;
        this.extendedPrice = extendedPrice;
        this.extendedPriceTime = extendedPriceTime;
        this.high = high;
        this.highSource = highSource;
        this.highTime = highTime;
        this.iexAskPrice = iexAskPrice;
        this.iexAskSize = iexAskSize;
        this.iexBidPrice = iexBidPrice;
        this.iexBidSize = iexBidSize;
        this.iexClose = iexClose;
        this.iexCloseTime = iexCloseTime;
        this.iexLastUpdated = iexLastUpdated;
        this.iexMarketPercent = iexMarketPercent;
        this.iexOpen = iexOpen;
        this.iexOpenTime = iexOpenTime;
        this.iexRealtimePrice = iexRealtimePrice;
        this.iexRealtimeSize = iexRealtimeSize;
        this.iexVolume = iexVolume;
        this.lastTradeTime = lastTradeTime;
        this.latestPrice = latestPrice;
        this.latestSource = latestSource;
        this.latestTime = latestTime;
        this.latestUpdate = latestUpdate;
        this.latestVolume = latestVolume;
        this.low = low;
        this.lowSource = lowSource;
        this.lowTime = lowTime;
        this.marketCap = marketCap;
        this.oddLotDelayedPrice = oddLotDelayedPrice;
        this.oddLotDelayedPriceTime = oddLotDelayedPriceTime;
        this.open = open;
        this.openTime = openTime;
        this.openSource = openSource;
        this.peRatio = peRatio;
        this.previousClose = previousClose;
        this.previousVolume = previousVolume;
        this.primaryExchange = primaryExchange;
        this.symbol = symbol;
        this.volume = volume;
        this.week52High = week52High;
        this.week52Low = week52Low;
        this.ytdChange = ytdChange;
        this.isUSMarketOpen = isUSMarketOpen;

    };
};
module.exports = { 
    Share 
};